image: maven:3.8-openjdk-11
default:
  tags:
    - dockerRunner

  stages:
    - test

Integration tests with Allure:
  stage: test
  script:
    - ./mvn clean test
    - ./mvn allure:report

  artifacts:
    paths:
    - target\site\allure-maven-plugin/*
